apiVersion: v1
kind: Secret
metadata:
  name: system-monitor-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZXhhbXBsZQ==         # example
  DB_USER: cm9vdA==                         # root
  DB_PASSWORD: ZXhhbXBsZQ==                 # example
  DB_NAME: c3lzaW5mbw==                     # sysinfo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-monitor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-monitor
  template:
    metadata:
      labels:
        app: system-monitor
    spec:
      containers:
        - name: mysql-server
          image: dktc419/info:db-IMAGE_TAG
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: system-monitor-secrets
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306

        - name: monitor-app
          image: dktc419/info:app-IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "localhost"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: system-monitor-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: system-monitor-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: system-monitor-secrets
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: monitor-app-service
spec:
  selector:
    app: system-monitor
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
